spring:
  ktor:
    port: 5461
  data:
    mongodb:
      uri: mongodb://localhost/qq
      auto-index-creation: true
  task:
    scheduling:
      pool:
        size: 10

kuku:
  mirai:
    qq:
    password:
    protocol: android_phone
    master: 734669014
